#!/bin/sh
# This script downloads, patches and builds grub4dos and downloads syslinux for GeeXboX installer for Windows.
# use '-n' to skip downloading
# Prepared files are stored in ./GeeXboX installer for Windows

syslinuxversion="3.63"

if (test "$1" != "-n" || ! (test -e ./grub4dos-snapshot.tar.gz)) && !(rm -f grub4dos-snapshot.tar.gz && wget http://svn.gna.org/daily/grub4dos-snapshot.tar.gz) ; then
  echo "Retrieving grub4dos sources failed !"
  exit 1
fi

if (test "$1" != "-n" || ! (test -e ./syslinux-$syslinuxversion.tar.gz)) && !(rm -f syslinux-$syslinuxversion.tar.gz && wget http://freshmeat.net/redir/syslinux/10177/url_tgz/syslinux-3.63.tar.gz) ; then
  echo "Retrieving syslinux sources failed !"
  exit 1
fi

if ! (tar -xf grub4dos-snapshot.tar.gz && tar -xf syslinux-$syslinuxversion.tar.gz) ; then
  echo "Extracting sources failed !"
  exit 1
fi

if !(cat ./grub4dos-geexbox.diff | patch -d grub4dos -p1) ; then
  echo "Error patching sources !"
  exit 1
fi

cd grub4dos
./configure --enable-preset-menu=preset_menu.lst
make -C stage2 grldr grldr.mbr grub.exe

cd ..
GEEXBOX="GeeXboX installer for Windows"
mkdir -p "$GEEXBOX"
cp -f grub4dos/stage2/grldr "$GEEXBOX/gxldr"
cp -f grub4dos/stage2/grldr.mbr "$GEEXBOX/gxldr.mbr"
cp -f grub4dos/stage2/grub.exe "$GEEXBOX/gxgrub.exe"
cp -f syslinux-$syslinuxversion/win32/syslinux.exe "$GEEXBOX/syslinux.exe"
echo "grub4dos and syslinux files have been saved to \".\\$GEEXBOX\""
exit 0


